@SET LOCAL_VARS_SCRIPT_LOADED=True
@SET BDS_LOCAL=C:\Program Files (x86)\Embarcadero\Studio\21.0
@SET BDSCOMMONDIR_LOCAL=C:\Users\Public\Documents\Embarcadero\Studio\21.0
@SET MADEXCEPT_TOOLS_LOCAL=C:\Program Files (x86)\madCollection\madExcept\Tools
@SET ISC_DIR_LOCAL=C:\Program Files (x86)\Inno Setup 6
@SET LAZARUS_LINUX_LOCAL=C:\fpcupdeluxe\fpcdeluxe_3.0.0_1.8.0\lazarus
@SET FrameworkDir_LOCAL=C:\Windows\Microsoft.NET\Framework\v4.0.30319
@SET FrameworkVersion_LOCAL=v4.0
@SET FrameworkSDKDir_LOCAL=
@SET KMRMapsRepoDir_LOCAL=F:\Development_Win7\Repos\kam_remake_maps
@SET KMRPrivateRepoDir_LOCAL=F:\Development_Win7\Repos\kam_remake_private
@SET KMRResourcesRepoDir_LOCAL=F:\Development_Win7\Repos\kam_remake_resources
@SET KaMOrigDir_LOCAL=F:\Games\KaM The Peasants Rebellion
@SET KMRPrevVersionDir_LOCAL=F:\games\KaM Remake
@SET SpritesRXADir_LOCAL=C:\Games\KaM Remake Beta r13651\data\Sprites
@SET ScriptingEditorDir_LOCAL=F:\Development_Win7\Repos\ScriptingEditor
@SET BuildFullDir_LOCAL=F:\KaM_Remake Beta
